---
title: j-claw
---
stateDiagram
    state "approve" as approve
    state "classify" as classify {
        state "setupTask" as setupTask
        state "nodeCallLLM" as nodeCallLLM
        state "nodeDecide" as nodeDecide
        state "callToolsHacked" as callToolsHacked
        state "handleAssistantMessage" as handleAssistantMessage
        state "finalizeTask" as finalizeTask
        state "sendToolsResults" as sendToolsResults

        [*] --> setupTask
        setupTask --> nodeCallLLM
        nodeCallLLM --> nodeDecide
        nodeDecide --> callToolsHacked : transformed
        nodeDecide --> handleAssistantMessage : transformed
        nodeDecide --> [*] : transformed
        callToolsHacked --> finalizeTask : onCondition
        callToolsHacked --> sendToolsResults
        handleAssistantMessage --> nodeDecide
        finalizeTask --> [*]
        sendToolsResults --> nodeDecide
    }
    state "identify" as identify {
        state "setupTask" as setupTask
        state "nodeCallLLM" as nodeCallLLM
        state "nodeDecide" as nodeDecide
        state "callToolsHacked" as callToolsHacked
        state "handleAssistantMessage" as handleAssistantMessage
        state "finalizeTask" as finalizeTask
        state "sendToolsResults" as sendToolsResults

        [*] --> setupTask
        setupTask --> nodeCallLLM
        nodeCallLLM --> nodeDecide
        nodeDecide --> callToolsHacked : transformed
        nodeDecide --> handleAssistantMessage : transformed
        nodeDecide --> [*] : transformed
        callToolsHacked --> finalizeTask : onCondition
        callToolsHacked --> sendToolsResults
        handleAssistantMessage --> nodeDecide
        finalizeTask --> [*]
        sendToolsResults --> nodeDecide
    }
    state "chatReply" as chatReply {
        state "setupTask" as setupTask
        state "nodeCallLLM" as nodeCallLLM
        state "nodeDecide" as nodeDecide
        state "callToolsHacked" as callToolsHacked
        state "handleAssistantMessage" as handleAssistantMessage
        state "finalizeTask" as finalizeTask
        state "sendToolsResults" as sendToolsResults

        [*] --> setupTask
        setupTask --> nodeCallLLM
        nodeCallLLM --> nodeDecide
        nodeDecide --> callToolsHacked : transformed
        nodeDecide --> handleAssistantMessage : transformed
        nodeDecide --> [*] : transformed
        callToolsHacked --> finalizeTask : onCondition
        callToolsHacked --> sendToolsResults
        handleAssistantMessage --> nodeDecide
        finalizeTask --> [*]
        sendToolsResults --> nodeDecide
    }
    state "deploy" as deploy {
        state "setupTask" as setupTask
        state "nodeCallLLM" as nodeCallLLM
        state "nodeDecide" as nodeDecide
        state "callToolsHacked" as callToolsHacked
        state "handleAssistantMessage" as handleAssistantMessage
        state "finalizeTask" as finalizeTask
        state "sendToolsResults" as sendToolsResults

        [*] --> setupTask
        setupTask --> nodeCallLLM
        nodeCallLLM --> nodeDecide
        nodeDecide --> callToolsHacked : transformed
        nodeDecide --> handleAssistantMessage : transformed
        nodeDecide --> [*] : transformed
        callToolsHacked --> finalizeTask : onCondition
        callToolsHacked --> sendToolsResults
        handleAssistantMessage --> nodeDecide
        finalizeTask --> [*]
        sendToolsResults --> nodeDecide
    }
    state "verify" as verify {
        state "saveInput" as saveInput
        state "provideResult" as provideResult
        state "verifyTask" as verifyTask {
            state "setupTask" as setupTask
            state "nodeCallLLM" as nodeCallLLM
            state "nodeDecide" as nodeDecide
            state "callToolsHacked" as callToolsHacked
            state "handleAssistantMessage" as handleAssistantMessage
            state "finalizeTask" as finalizeTask
            state "sendToolsResults" as sendToolsResults

            [*] --> setupTask
            setupTask --> nodeCallLLM
            nodeCallLLM --> nodeDecide
            nodeDecide --> callToolsHacked : transformed
            nodeDecide --> handleAssistantMessage : transformed
            nodeDecide --> [*] : transformed
            callToolsHacked --> finalizeTask : onCondition
            callToolsHacked --> sendToolsResults
            handleAssistantMessage --> nodeDecide
            finalizeTask --> [*]
            sendToolsResults --> nodeDecide
        }

        [*] --> saveInput
        saveInput --> verifyTask
        verifyTask --> provideResult
        provideResult --> [*]
    }
    state "refine" as refine {
        state "setupTask" as setupTask
        state "nodeCallLLM" as nodeCallLLM
        state "nodeDecide" as nodeDecide
        state "callToolsHacked" as callToolsHacked
        state "handleAssistantMessage" as handleAssistantMessage
        state "finalizeTask" as finalizeTask
        state "sendToolsResults" as sendToolsResults

        [*] --> setupTask
        setupTask --> nodeCallLLM
        nodeCallLLM --> nodeDecide
        nodeDecide --> callToolsHacked : transformed
        nodeDecide --> handleAssistantMessage : transformed
        nodeDecide --> [*] : transformed
        callToolsHacked --> finalizeTask : onCondition
        callToolsHacked --> sendToolsResults
        handleAssistantMessage --> nodeDecide
        finalizeTask --> [*]
        sendToolsResults --> nodeDecide
    }

    [*] --> classify
    classify --> identify : transformed
    classify --> chatReply : transformed
    identify --> deploy
    chatReply --> [*] : transformed
    deploy --> verify
    verify --> approve : transformed
    verify --> refine : transformed
    verify --> [*] : transformed
    approve --> [*] : transformed
    refine --> verify